### ISSUE TITLE
getting 301 error

### ISSUE THREAD

**Issue by schosterbarak** [mislav/bump-homebrew-formula-action#13]
i have configured the following github action:
```
name: homebrew

on:
  push:
    branches:
      - '*'
    tags: 
      - '*'

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - name: Get release version
        id: get_version
        run: |
          sleep 10m
          checkov_version=$(curl -sL https://api.github.com/repos/bridgecrewio/checkov/tags | jq -r '.[0]["name"]' )
          echo ::set-env name=RELEASE_VERSION::$(echo $checkov_version)
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          # A PR will be sent to github.com/Homebrew/homebrew-core to update this formula:
          formula-name: checkov
          download-url: https://pypi.io/packages/source/c/checkov/checkov-${{ env.RELEASE_VERSION }}.tar.gz
        env:
          COMMITTER_TOKEN: ${{ secrets.PAT_TOKEN }}
```
and I'm getting the following:
```
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'PAT_TOKEN'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating condition for step: 'Run mislav/bump-homebrew-formula-action@v1'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Run mislav/bump-homebrew-formula-action@v1
##[debug]Loading inputs
##[debug]Evaluating: format('https://pypi.io/packages/source/c/checkov/checkov-{0}.tar.gz', env.RELEASE_VERSION)
##[debug]Evaluating format:
##[debug]..Evaluating String:
##[debug]..=> 'https://pypi.io/packages/source/c/checkov/checkov-{0}.tar.gz'
##[debug]..Evaluating Index:
##[debug]....Evaluating env:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'RELEASE_VERSION'
##[debug]..=> '1.0.755'
##[debug]=> 'https://pypi.io/packages/source/c/checkov/checkov-1.0.755.tar.gz'
##[debug]Result: 'https://pypi.io/packages/source/c/checkov/checkov-1.0.755.tar.gz'
##[debug]Loading env
Run mislav/bump-homebrew-formula-action@v1
  with:
    formula-name: checkov
    download-url: https://pypi.io/packages/source/c/checkov/checkov-1.0.755.tar.gz
    homebrew-tap: Homebrew/homebrew-core
    commit-message: {{formulaName}} {{version}}
  
  Created by https://github.com/mislav/bump-homebrew-formula-action
  
  env:
    RELEASE_VERSION: 1.0.755
    COMMITTER_TOKEN: ***
##[debug]GET https://pypi.io/packages/source/c/checkov/checkov-1.0.755.tar.gz

/home/runner/work/_actions/mislav/bump-homebrew-formula-action/v1/src/calculate-download-checksum.ts:13
                throw new Error(`HTTP ${res.statusCode}`);
^
Error: HTTP 301
    at ClientRequest.<anonymous> (/home/runner/work/_actions/mislav/bump-homebrew-formula-action/v1/src/calculate-download-checksum.ts:13:1)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:210:5)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
    at TLSSocket.socketOnData (_http_client.js:456:22)
    at TLSSocket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Run mislav/bump-homebrew-formula-action@v1
```

any idea what am i doing wrong?

**Comment by mislav** [comment]
Thank you for reporting. You're not doing anything wrong. It appears that `https://pypi.io/packages/source/c/checkov/checkov-1.0.755.tar.gz` has several layers of nested redirects before being resolved to a final file, but the code seems to be handling only the 1st redirect and choking on the subsequent one.

**Comment by schosterbarak** [comment]
@mislav any suggestion for a workaround there?

**Comment by mislav** [comment]
Releasing a fix
