### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by arzg** [mislav/bump-homebrew-formula-action#16]
Hi, thanks for the GitHub Action, it’s worked perfectly so far! I’ve just run into a syntax error when trying to use this action (v1.11), which you can see [here](https://github.com/CookieCoder15/pipes-rs/runs/2012681850). I’ve reproduced the error message below:

```
Run mislav/bump-homebrew-formula-action@v1.11
/Users/runner/work/_actions/mislav/bump-homebrew-formula-action/v1.11/lib/index.js:5910
        request: { fetch: options?.fetch },
                                  ^

SyntaxError: Unexpected token '.'
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

I’ve also located [the offending line](https://github.com/mislav/bump-homebrew-formula-action/blob/b89695ef915c409ecd16d90d9ddba3cd983708ac/src/api.ts#L14), which was introduced in 11ce557d.

**Comment by mislav** [comment]
Ouch! Thank you for the detailed report 💯

**Comment by arzg** [comment]
All good :)
